### ISSUE TITLE
Lua comments automatically duplicated to new line on Enter

### ISSUE THREAD

**Issue by JoseConseco** [terrortylor/nvim-comment#10]
When I have cursor in commented line (lua script), after pressing enter - the comment is automatically duplicated to new line like so:
![obraz](https://user-images.githubusercontent.com/13521338/112811822-bf043300-907c-11eb-914d-e16b0ebaa6f3.png)
Does not happen for python. Did not test with other languages. 
If it could be made consistent between nanguages, and option to disable it pernamently (if it is not bug)

**Comment by cloggier** [comment]
Check your `formatoptions`, you most likely have `r` set on lua, but not python.

**Comment by JoseConseco** [comment]
thx. My bad I thought it was caused by your plug. I just  educated myself about 
`set formatoptions-=cro`
And after an hour wasted solution seems to be: create   .config/nvim/after/ftplugin/lua.vim    and put above line iside.
Otherwise other ftpscripts may override it. Damm vim is convoluted.

**Comment by cloggier** [comment]
Use 'setlocal` instead of `set` there, otherwise it will change that setting globally rather than just for that buffer.
