### ISSUE TITLE
Maintain indents over range

### ISSUE THREAD

**Issue by YodaEmbedding** [terrortylor/nvim-comment#2]
Visually select and `:CommentToggle` over the following python test case:

```python
def edgar(x):
    print("Once upon a midnight dreary")
```

Actual:

```python
    # def edgar(x):
    # print("Once upon a midnight dreary")
```

Expected:

```python
# def edgar(x):
#     print("Once upon a midnight dreary")
```

**Comment by terrortylor** [comment]
I believe this is fixed now, please re-test

**Comment by terrortylor** [comment]
My testing based on your provided input passes, going to close. Thanks for raising the issue.
