### ISSUE TITLE
Custom mapping is broken

### ISSUE THREAD

**Issue by khalidchawtany** [terrortylor/nvim-comment#20]
I use the following to configure nvim-comment. After I updated today my mappings broke. I think it was caused by this commit 
https://github.com/terrortylor/nvim-comment/commit/22f81f96d75f5cf8eb2e19ebbb0c6f37f32cec2a
```lua

require('nvim_comment').setup({
    marker_padding = true,
    comment_empty = true
    create_mappings = true
    line_mapping = "<leader>cc",zzzzzzz
    operator_mapping = "<leader>c"
})
````

**Comment by terrortylor** [comment]
Hey is your leader mapped to space?
`:h normal

{commands} cannot start with a space.  Put a count of
1 (one) before it, "1 " is one space.`

Pushed a fix, FYI your config above has syntax issues, should be:
`require('nvim_comment').setup({
    marker_padding = true,
    comment_empty = true,
    create_mappings = true,
    line_mapping = "<leader>cc",
    operator_mapping = "<leader>c"
})`

**Comment by khalidchawtany** [comment]
Yup my leader is mapped to space and reported  this late last night so I was sleepy :)

thanks for the fix, will test it when I get back to my computer
