### ISSUE TITLE
toml files using wrong commentstring

### ISSUE THREAD

**Issue by ChristianChiarulli** [terrortylor/nvim-comment#29]
toml files seem to use `/* */` pattern when the should use `#`

**Comment by terrortylor** [comment]
Hey, neovim doesn't seem to have a toml filetype in the runtime: https://github.com/neovim/neovim/tree/master/runtime/ftplugin
So it seems to default to `/* */`
As this plugin doesn't set the commentstring value but uses what is set, you'll have to set this your self. If you look under the Configure section of the readme there are a few ways sepcified this can be set (Changing/Setting commentstring).
Personnaly I would create a local ftplugin/toml.lua file and have it set there (the last example).

Closing as this isn't a big of the plugin.
Please re-open if you are still having issues.
