### ISSUE TITLE
Allow commenting single empty lines

### ISSUE THREAD

**Issue by mvllow** [terrortylor/nvim-comment#33]
I thought `comment_empty` would enable this behaviour but it doesn't seem to do so.

In the below example, highlighting all 3 lines and running `:CommentToggle` has the expected result of commenting each line. If you put your cursor on line 2 (empty), however, and run `:CommentToggle`, no comment is created.

```lua
1  local pitaya = 'fruit'
2  
3  local carrot = 'veggie'
```

It would be lovely if we were able to comment a single empty line, eg. for starting a new comment instead of commenting existing text 🥰

**Comment by terrortylor** [comment]
set comment_empty to true, see README.md
