### ISSUE TITLE
line_mapping and operator_mapping with the same key mapping

### ISSUE THREAD

**Issue by cseelus** [terrortylor/nvim-comment#38]
I tried to assign the same mapping to `line_mapping` and `operator_mapping`, like with vim-commentary, but unfortunately this doesn't work:

```lua
require('nvim_comment').setup({
    -- Should key mappings be created
    create_mappings = true,
    -- Normal mode mapping left hand side
    line_mapping = '<leader>c',
    -- Visual/Operator mapping left hand side
    operator_mapping = '<leader>c'
})
```

Am I missing something or is this (currently) not possible with nvim-comment out of the box?

**Comment by Markus00000** [comment]
I encountered the same issue. A workaround:

    vim.api.nvim_set_keymap('n', '<leader>c', ':CommentToggle<CR>', {noremap = true, silent = true})
    vim.api.nvim_set_keymap('v', '<leader>c', ":'<,'>CommentToggle<CR>", {noremap = true, silent = true})

**Comment by terrortylor** [comment]
Closing as this is not supported, the `line_mapping` being a shortcut for the `operator_mapping` against a line.
