### ISSUE TITLE
Comments with no indent are not toggled

### ISSUE THREAD

**Issue by niceloaf** [terrortylor/nvim-comment#4]
Anything with a comment that has no indent is not toggled, like this  for example:
```lua
--local test = 0
```

Actual:
```lua
-- --local test = 0
```

Expected:
```lua
local test = 0
```

This also happens with any language with a comment that has no indent.

**Comment by terrortylor** [comment]
I'm unable to replicate this issue, can you see if it still persists when you are using latest commit and you load a file with:
` vi -u NONE <SOME FILE GOES HERE> -c "packadd nvim-comment | lua require('nvim_comment').setup()"`
Note that this assumes that you plugin is in the 'opt' directory and usings vim's default package manager stucture.

**Comment by niceloaf** [comment]
Yep, it still happens.

**Comment by terrortylor** [comment]
Oh couldn't see the wood for the trees!
It assumes there is a space between the space and the rest of the line.
If you don't have the padding them there is a setting you can use to not
use the padding.

require('nvim_comment').setup({marker_padding = false })

**Comment by niceloaf** [comment]
Oh that makes sense now, thanks!

**Comment by SaraSmiseth** [comment]
I have the same issue.
Setting `marker_padding` to `false` does not solve it for me because I actually want the space between marker and comment.

Toggling the following two comments

``` lua
--local test = 0
-- local test = 0
```

should uncomment both:

``` lua
local test = 0
local test = 0
```

And toggling again should give me:

``` lua
-- local test = 0
-- local test = 0
```

Is this somehow possible?

**Comment by tkkcc** [comment]
same issue as @SaraSmiseth, kommentary and vim-commentary does it correct.
