### ISSUE TITLE
Wrong comment string for .nix files

### ISSUE THREAD

**Issue by GaetanLepage** [terrortylor/nvim-comment#42]
When using the plugin inside `.nix` files, the inserted comment string is `/* ... */` while it should be `#`.

Is it actually the job of this plugin to handle this ? Are the _default_ `commentstring` values defined elsewhere ?

Thank you for your consideration.

**Comment by terrortylor** [comment]
Hey, sorry been AWOL.
No, this plugin doesn't manage the `commentstring` values, it uses vim/neovim's values, so if you want to change this behaviour you need to do this your self. There are some examples in the readme, good luck!
