### ISSUE TITLE
Allows to use the same operator for normal and visual mode

### ISSUE THREAD

**Issue by navakelvin** [terrortylor/nvim-comment#52]
It seems you can't use the same operator for normal and visual mode.

Can you implement that?

**Comment by navakelvin** [comment]
Don't worry, I was able to fix it by assigning the `CommentToggle` command to the desired keys.

**Comment by jensenojs** [comment]
@navakelvin would you please kindly teach me how to do that?

**Comment by jensenojs** [comment]
okay, i do this by mapping <c-\\> to :CommentToggle<CR> in both normal and visual mode, thanks!
