### ISSUE TITLE
Handlebars support

### ISSUE THREAD

**Issue by ziulev** [terrortylor/nvim-comment#7]
[https://handlebarsjs.com/](handlebarsjs)

I could do `autocmd FileType html.handlebars setlocal commentstring={{!--\ %s\ --}}` for [kommentary plugin](https://github.com/b3nj5m1n/kommentary)
Is there a way to configure nvim-comment for handlebars?

**Comment by terrortylor** [comment]
Hi @ziulev the commentstring option is also used by nvim-comment, the same autocommand should work for nvim-comment.
If it's not, can you check the output of commentstring option when in a handle bars file:
`set commentstring?`

If it's not as desired check that the buffers filetype is also as expected:
`set filetype?`

**Comment by terrortylor** [comment]
Hey gonna close as not heard back, reopen if you are still having issues though
