### ISSUE TITLE
Make dot repeatable

### ISSUE THREAD

**Issue by cloggier** [terrortylor/nvim-comment#8]
Hi, do you think commenting, uncommenting or toggling could be made `.` repeatable?

**Comment by terrortylor** [comment]
Hey,
I have dot repeatability working on my machine at least where I've quickly tested, i.e.
- gcl (comment current line)
- gcip (comment paragraph)

Reckon you could give me a some details on how to replicate the issue you are having or where it's not working for you. I can try to take a look.

**Comment by cloggier** [comment]
Ah, two mappings you mentioned do work indeed, but `gcc` does not. At least for me, does but work for you?

**Comment by terrortylor** [comment]
Ahh, ofcourse... hmm tbh reckon mapping gcc to gcl would be easiest... 
Will have a play one evening this week, thanks for letting me know!

**Comment by terrortylor** [comment]
hey I've finally got around to make that simple change, sorry been busy. dot repeatable on `gcc`

**Comment by cloggier** [comment]
Awesome, thank you so much!
