### ISSUE TITLE
Custom mapping

### ISSUE THREAD

**Issue by cloggier** [terrortylor/nvim-comment#9]
Hey again.

I have used tcomment for a long time and gotten used to `<C-_><C-_>` mapping. So I did set `line_mapping` to it

```lua
line_mapping = "<C-_><C-_>"
```

it works fine except for *visual mode*. tcomment did support that, I know there is `operator_mapping` but I would like to keep that set to default value.

Do you think I could somehow map `<C-_><C-_>` to toggle single line in normal mode and selection in visual mode too?

Thanks!

**Comment by JosefLitos** [comment]
you can use ```map("n", "<C-_>", ":CommentToggle<CR>", {noremap=true,silent=true})``

**Comment by terrortylor** [comment]
Hey, yeah this works:
`nmap <C-_><C-_> :CommentToggle<CR>`

Doesn't handle your other issue though. Been busy am still planning on getting to it!

**Comment by JosefLitos** [comment]
> Hey, yeah this works:
> `nmap <C-_><C-_> :CommentToggle<CR>`
> 
> Doesn't handle your other issue though. Been busy am still planning on getting to it!

For visual mode just use map instead of nmap (map is for n, v and o modes, nmap only for normal mode)
